import assert from "node:assert/strict";
import test from "node:test";

import {
  createClaspConfig,
  createDeploymentMatrix,
  createTargetSource,
  loadProjectRegistry,
  parseProjectRegistry,
  validateReleaseTag,
} from "../tool/project-registry.mjs";

test("project registry exposes every deployment target", () => {
  assert.deepEqual(loadProjectRegistry(), [
    {
      slug: "cardhub",
      environment: "apps-script-cardhub-production",
    },
  ]);
});

test("one release tag resolves every registered project", () => {
  assert.equal(validateReleaseTag("v0.0.1"), "v0.0.1");
  const projects = parseProjectRegistry({
    projects: [
      { slug: "tetradka", environment: "apps-script-production" },
      {
        slug: "second-project",
        environment: "apps-script-second-production",
      },
    ],
  });

  assert.deepEqual(createDeploymentMatrix(projects), {
    include: [
      {
        project: "tetradka",
        environment: "apps-script-production",
      },
      {
        project: "second-project",
        environment: "apps-script-second-production",
      },
    ],
  });
});

test("project-specific and malformed release tags are rejected", () => {
  assert.throws(() => validateReleaseTag("tetradka-v0.0.1"), /vX\.Y\.Z/);
  assert.throws(() => validateReleaseTag("v0.0"), /vX\.Y\.Z/);
});

test("registry rejects duplicate or unsafe project targets", () => {
  assert.throws(
    () =>
      parseProjectRegistry({
        projects: [
          { slug: "first", environment: "apps-script-first-production" },
          { slug: "first", environment: "apps-script-second-production" },
        ],
      }),
    /duplicated/,
  );

  assert.throws(
    () =>
      parseProjectRegistry({
        projects: [
          { slug: "../escape", environment: "apps-script-production" },
        ],
      }),
    /invalid slug/,
  );

  assert.throws(
    () =>
      parseProjectRegistry({
        projects: [{ slug: "first", environment: "unrelated-production" }],
      }),
    /invalid GitHub Environment/,
  );
});

test("registry requires one unique environment per project", () => {
  assert.throws(
    () =>
      parseProjectRegistry({
        projects: [
          { slug: "first", environment: "apps-script-production" },
          { slug: "second", environment: "apps-script-production" },
        ],
      }),
    /assigned more than once/,
  );
});

test("clasp configuration accepts only a non-empty Apps Script ID", () => {
  assert.deepEqual(createClaspConfig("example_apps_script_id_1234567890"), {
    scriptId: "example_apps_script_id_1234567890",
    rootDir: "src",
  });

  assert.throws(() => createClaspConfig(""), /missing or invalid/);
  assert.throws(
    () => createClaspConfig("id with whitespace"),
    /missing or invalid/,
  );
});

test("target source is generated only from a valid spreadsheet ID and title", () => {
  const source = createTargetSource(
    "example_spreadsheet_id_1234567890",
    'title "quoted"',
  );

  assert.match(source, /^\/\/ Generated by `npm run project:configure`/);
  assert.match(
    source,
    /const TARGET_SPREADSHEET = Object\.freeze\(\{"id":"example_spreadsheet_id_1234567890","title":"title \\"quoted\\""\}\);/,
  );

  assert.throws(
    () => createTargetSource("", "title"),
    /SPREADSHEET_ID is missing or invalid/,
  );
  assert.throws(
    () => createTargetSource("id with whitespace", "title"),
    /SPREADSHEET_ID is missing or invalid/,
  );
  assert.throws(
    () => createTargetSource("example_spreadsheet_id_1234567890", "  "),
    /SPREADSHEET_TITLE is missing or invalid/,
  );
});
